### ISSUE TITLE
User Story 13: View a customer's address on Google Maps

### ISSUE THREAD

**Issue by jonleeyz** [CS2103JAN2018-F12-B4/main#22]
As a **User**, I want to **view a customer's address on Google Maps** so that I can **visualise the location of the customer**.

**Comment by melvintzw** [comment]
should we close this PR? @CS2103JAN2018-F12-B4/developers

**Comment by melvintzw** [comment]
@zhangriqi remember to update the developer guide and user guide with the new locate command!

**Comment by zhangriqi** [comment]
@melvintzw Thanks! Will do it.
