### ISSUE TITLE
Documentation: v1.1

### ISSUE THREAD

**Issue by jonleeyz** [CS2103JAN2018-F12-B4/main#41]
Update the following pages:
- **User Guide**:
   - Update the user guide to describe what the product would be like when it is at 2.0. Mark features not implemented yet as Coming in v2.0. You may use UI mockups where necessary.
- **About Us page**:
   - This page is used for module admin purposes. Please follow the format closely to avoid penalties. 
   - Replace info of SE-EDU developers with info of your team, including a suitable photo as described here.
   - Including the name/photo of the supervisor/lecturer is optional.
   - The photo of a team member should be `doc/images/githbub_username_in_lower_case.png` e.g. `docs/images/damithc.png`.
   - Indicate the different roles played and responsibilities held by each team member. You can reassign these roles and responsibilities later in the project, if necessary.
- **README.adoc** page: Update it to match your project. 
   - Add a UI mockup of your intended final product.
   - Note that the image of the UI should be `docs/images/Ui.png` so that it can be downloaded by our scripts.
   - The original `README.adoc` file (which doubles as the landing page of your project website) is written to read like the introduction to an SE learning/teaching resource. You should restructure this page to look like the home page of a real product (not a school project) targeting real users  e.g. remove references to addressbook-level3, Learning Outcomes etc. mention target users, add a marketing blurb etc. 
   - On a related note, also remove `Learning Outcomes` link and related pages.
Acknowledge the original source of the code i.e. AddressBook-Level4 project created by SE-EDU initiative at `https://github.com/se-edu/`.

Reference: [W8.2: Can describe a product from the user's perspective](https://nus-cs2103-ay1718s2.github.io/website/index.html)

**Comment by melvintzw** [comment]
Done. Remember to update UserGuide and DeveloperGuide weekly!
