### ISSUE TITLE
Modify AddCommand to quickly add Runner or Customer

### ISSUE THREAD

**Issue by jonleeyz** [CS2103JAN2018-F12-B4/main#62]
Modify `AddCommand` to quickly add a new `Runner` or `Customer` object.
- [ ] Language processing
- [ ] Auto tagging

**Comment by melvintzw** [comment]
@jonleeyz are we doing this?

**Comment by melvintzw** [comment]
@jonleeyz closing this as it is a non-critical enhancement that could be defered to v2.0
