### ISSUE TITLE
Possible Targeted-User Specific Features

### ISSUE THREAD

**Issue by jonleeyz** [CS2103JAN2018-F12-B4/main#73]
- [ ] Show all `Runners` with one command / keyboard shortcut
- [ ] Show all `Customers` with one command / keyboard shortcut
- [ ] Mark all jobs of a certain tag done
- [ ] Mark all jobs assigned to a certain `Runner` done
- [ ] Assign selected jobs to a `Runner`
- [ ] Tag multiple `Customers` at once with one or more tags
- [ ] Tag multiple `Runners` at once with one or more tags
- [ ] Clear one or more tags from multiple `Customers` at once
- [ ] Clear one or more tags from multiple `Runners` at once
- [ ] Auto updating interest rates and actions to be taken

**Comment by melvintzw** [comment]
Defer to v2.0?
