### ISSUE TITLE
Fail tests after adding google search

### ISSUE THREAD

**Issue by zhangriqi** [CS2103JAN2018-F12-B4/main#8]
#6 Failed to pass the tests, but all the tests passed in IntelliJ if not ran in the headless mode.

travis log is like this:
systemtests.AddCommandSystemTest > classMethod FAILED
    java.lang.RuntimeException
        Caused by: java.lang.UnsupportedOperationException

**Comment by jonleeyz** [comment]
The updated associated pull request has been approved and merged.

Closing this issue.
