### ISSUE TITLE
Write JUnit Tests for keyboard shortcuts

### ISSUE THREAD

**Issue by jonleeyz** [CS2103JAN2018-F12-B4/main#96]
- [x] AddCommand
- [x] AssignCommand
- [x] ClearCommand
- [x] DeleteCommand
- [x] EditCommand
- [x] FindCommand
- [ ] HomeCommand
- [ ] HistoryCommand
- [ ] ListCommand
- [x] LocateCommand
- [ ] RedoCommand
- [x] SearchCommand
- [ ] UndoCommand

**Comment by jonleeyz** [comment]
Partially resolved by PR #109. 

But other tests not implemented yet, so issue remains open.

**Comment by jonleeyz** [comment]
Hey @zhangriqi, @melvintzw, need y'all to write tests for the `LocateCommand` and `AssignCommand` respectively!

**Comment by zhangriqi** [comment]
Thanks! Will do.

**Comment by jonleeyz** [comment]
All needed tests completed. Closed.
